import "server-only";
import { Document, Page, View, Text, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10, fontFamily: "Helvetica", color: "#0B0F19" },
  headerRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 28 },
  brand: { fontSize: 16, fontWeight: 700 },
  brandSub: { fontSize: 8, color: "#5B6472", marginTop: 2 },
  title: { fontSize: 13, fontWeight: 700, color: "#0F9D63", textAlign: "right" },
  number: { fontSize: 9, color: "#5B6472", textAlign: "right", marginTop: 2 },
  amountBox: { alignItems: "center", padding: 28, backgroundColor: "#F7F8FA", borderRadius: 8, marginBottom: 24 },
  amountLabel: { fontSize: 9, color: "#5B6472", marginBottom: 6 },
  amount: { fontSize: 26, fontWeight: 700, color: "#0F9D63" },
  row: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 6, borderBottom: "0.5 solid #EEF0F4" },
  label: { fontSize: 9, color: "#5B6472" },
  value: { fontSize: 10, color: "#0B0F19", fontWeight: 700 },
  footer: { position: "absolute", bottom: 24, left: 40, right: 40, fontSize: 7.5, color: "#94A0B2", textAlign: "center" },
});

function kes(n: number): string {
  return `KES ${new Intl.NumberFormat("en-KE", { maximumFractionDigits: 0 }).format(n)}`;
}

export interface ReceiptPdfProps {
  number: string;
  issuedAt: Date;
  companyName: string;
  amount: number;
  method: string;
  gatewayReference: string | null;
  documentNumber: string;
  remainingBalance: number;
}

export function ReceiptPdf(p: ReceiptPdfProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.headerRow}>
          <View>
            <Text style={styles.brand}>TECHFIND CONSULTING LIMITED</Text>
            <Text style={styles.brandSub}>Nairobi, Kenya · techfind.co.ke</Text>
          </View>
          <View>
            <Text style={styles.title}>RECEIPT</Text>
            <Text style={styles.number}>{p.number}</Text>
          </View>
        </View>

        <View style={styles.amountBox}>
          <Text style={styles.amountLabel}>Amount Received</Text>
          <Text style={styles.amount}>{kes(p.amount)}</Text>
        </View>

        <View style={styles.row}><Text style={styles.label}>Customer</Text><Text style={styles.value}>{p.companyName}</Text></View>
        <View style={styles.row}><Text style={styles.label}>Date</Text><Text style={styles.value}>{p.issuedAt.toLocaleDateString("en-KE", { year: "numeric", month: "long", day: "numeric" })}</Text></View>
        <View style={styles.row}><Text style={styles.label}>Payment Method</Text><Text style={styles.value}>{p.method}</Text></View>
        {p.gatewayReference && <View style={styles.row}><Text style={styles.label}>Transaction Reference</Text><Text style={styles.value}>{p.gatewayReference}</Text></View>}
        <View style={styles.row}><Text style={styles.label}>Proforma / Invoice</Text><Text style={styles.value}>{p.documentNumber}</Text></View>
        <View style={styles.row}><Text style={styles.label}>Remaining Balance</Text><Text style={styles.value}>{kes(p.remainingBalance)}</Text></View>

        <Text style={styles.footer}>Techfind Consulting Limited · This receipt was generated by Techfind Revenue OS</Text>
      </Page>
    </Document>
  );
}
