/**
 * Money fields are stored as `Decimal` in Postgres (see docs/DATABASE.md)
 * but the `db` client (src/server/db.ts) transparently converts them back
 * to `number` on every read via a result extension — so at runtime every
 * money field really is a `number`. The raw types generated by
 * `@prisma/client`, though, still say `Decimal` (they're generated from
 * the schema, not from the extended client), which is a lie for any type
 * built from them. Client Components can't receive a `Prisma.Decimal`
 * instance as a prop anyway (it's not a plain serializable value), so
 * every composite prop type built from these models re-declares its
 * money field(s) as `number` using the aliases below instead of importing
 * the raw model type directly.
 */
import type {
  Lead,
  Deal,
  QuickItem,
  Package as PackageModel,
  ProductFootprint,
  SalesDocument,
  SalesDocumentItem,
  PaymentSession,
  Payment,
  Receipt,
} from "@prisma/client";

export type LeadMoney = Omit<Lead, "value"> & { value: number };
export type DealMoney = Omit<Deal, "value"> & { value: number };
export type QuickItemMoney = Omit<QuickItem, "totalPrice"> & { totalPrice: number };
export type PackageMoney = Omit<PackageModel, "price"> & { price: number };
export type ProductFootprintMoney = Omit<ProductFootprint, "mrr"> & { mrr: number | null };

export type SalesDocumentMoney = Omit<
  SalesDocument,
  "subtotal" | "discount" | "taxAmount" | "total" | "depositRequired" | "balance" | "paidAmount"
> & {
  subtotal: number;
  discount: number;
  taxAmount: number;
  total: number;
  depositRequired: number;
  balance: number;
  paidAmount: number;
};

export type SalesDocumentItemMoney = Omit<SalesDocumentItem, "unitPrice" | "amount"> & {
  unitPrice: number;
  amount: number;
};

export type PaymentSessionMoney = Omit<PaymentSession, "amountDue"> & { amountDue: number };
export type PaymentMoney = Omit<Payment, "amount" | "refundedAmount"> & { amount: number; refundedAmount: number };
export type ReceiptMoney = Omit<Receipt, "amount"> & { amount: number };
